### ISSUE TITLE
[Task] 메인페이지 구현

### ISSUE THREAD

**Issue by choboeyo** [codestates/ganada#19]
#### Issue
- Group: `Client`
- Branch: feature/1-Main
- Deatil: 메인페이지 배너 및 컨텐츠 작업

#### TODO
- [ ]  메인 배너 캐로셀 구현
- [ ]  메인 컨텐츠 작업(지도, 위치 등등)
- [ ] 스크롤시 애니메이션 효과 넣어보기
- [ ] Header 구현
- [ ] Footer 구현
- [ ] 카테고리 구현
