### ISSUE TITLE
[Task] 모델, 사진작가 찾기 페이지 수정

### ISSUE THREAD

**Issue by tpgus** [codestates/ganada#53]
#### Issue
- Group: `Client`
- Branch: feature/1-search
- Deatil: 디자인, 기능 전면 재수정, 기존에는 페이지네이션을 이용해 데이터 목록 화면에 출력했지만, 이를 무한 스크롤로 변경하기.
정확한 라우팅 경로를 통해 데이터를 주고 받을 수 있도록 개선하기

#### TODO 
- [ ] 태그를 활용하여 어떠한 방식으로 데이터를 요청할 것인지에 대한 고민 및 구현
- [ ] 지도에 위치 표시
- [ ] 리액트 라우터에 대한 이해
